kind: pipeline
name: yapi

steps:
  - name: docker
    image: plugins/docker
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      repo: storezhang/yapi
      dockerfile: ./Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      force_tag: true
      tags:
        - 'latest'
        - '1.7.0.1'
